/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as AuthenticatedBrandStudioRouteImport } from './routes/_authenticated/brand-studio'
import { Route as AuthenticatedCarimbosRouteImport } from './routes/_authenticated/carimbos'
import { Route as AuthenticatedChapterLoopRouteImport } from './routes/_authenticated/chapter-loop'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedCheckOutRouteImport } from './routes/_authenticated/check-out'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedIdentidadeRouteImport } from './routes/_authenticated/identidade'
import { Route as AuthenticatedPassaporteRouteImport } from './routes/_authenticated/passaporte'
import { Route as AuthenticatedCarimbosColecaoRouteImport } from './routes/_authenticated/carimbos.colecao'
import { Route as AuthenticatedCheckInConfirmacaoRouteImport } from './routes/_authenticated/check-in.confirmacao'
import { Route as AuthenticatedCheckInScannerRouteImport } from './routes/_authenticated/check-in.scanner'
import { Route as AuthenticatedCheckOutCarimbadoRouteImport } from './routes/_authenticated/check-out.carimbado'
import { Route as AuthenticatedCheckOutSincronizarRouteImport } from './routes/_authenticated/check-out.sincronizar'
import { Route as AuthenticatedDiagnosticoInicialRouteImport } from './routes/_authenticated/diagnostico.inicial'
import { Route as AuthenticatedIdentidadeCartaoRouteImport } from './routes/_authenticated/identidade.cartao'
import { Route as AuthenticatedIdentidadePerfilRouteImport } from './routes/_authenticated/identidade.perfil'
import { Route as AuthenticatedPassaporteCapaRouteImport } from './routes/_authenticated/passaporte.capa'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtendimentoRoute =
  AuthenticatedAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandStudioRoute =
  AuthenticatedBrandStudioRouteImport.update({
    id: '/brand-studio',
    path: '/brand-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarimbosRoute = AuthenticatedCarimbosRouteImport.update({
  id: '/carimbos',
  path: '/carimbos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChapterLoopRoute =
  AuthenticatedChapterLoopRouteImport.update({
    id: '/chapter-loop',
    path: '/chapter-loop',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckOutRoute = AuthenticatedCheckOutRouteImport.update({
  id: '/check-out',
  path: '/check-out',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentidadeRoute = AuthenticatedIdentidadeRouteImport.update({
  id: '/identidade',
  path: '/identidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassaporteRoute = AuthenticatedPassaporteRouteImport.update({
  id: '/passaporte',
  path: '/passaporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarimbosColecaoRoute =
  AuthenticatedCarimbosColecaoRouteImport.update({
    id: '/colecao',
    path: '/colecao',
    getParentRoute: () => AuthenticatedCarimbosRoute,
  } as any)
const AuthenticatedCheckInConfirmacaoRoute =
  AuthenticatedCheckInConfirmacaoRouteImport.update({
    id: '/confirmacao',
    path: '/confirmacao',
    getParentRoute: () => AuthenticatedCheckInRoute,
  } as any)
const AuthenticatedCheckInScannerRoute =
  AuthenticatedCheckInScannerRouteImport.update({
    id: '/scanner',
    path: '/scanner',
    getParentRoute: () => AuthenticatedCheckInRoute,
  } as any)
const AuthenticatedCheckOutCarimbadoRoute =
  AuthenticatedCheckOutCarimbadoRouteImport.update({
    id: '/carimbado',
    path: '/carimbado',
    getParentRoute: () => AuthenticatedCheckOutRoute,
  } as any)
const AuthenticatedCheckOutSincronizarRoute =
  AuthenticatedCheckOutSincronizarRouteImport.update({
    id: '/sincronizar',
    path: '/sincronizar',
    getParentRoute: () => AuthenticatedCheckOutRoute,
  } as any)
const AuthenticatedDiagnosticoInicialRoute =
  AuthenticatedDiagnosticoInicialRouteImport.update({
    id: '/inicial',
    path: '/inicial',
    getParentRoute: () => AuthenticatedDiagnosticoRoute,
  } as any)
const AuthenticatedIdentidadeCartaoRoute =
  AuthenticatedIdentidadeCartaoRouteImport.update({
    id: '/cartao',
    path: '/cartao',
    getParentRoute: () => AuthenticatedIdentidadeRoute,
  } as any)
const AuthenticatedIdentidadePerfilRoute =
  AuthenticatedIdentidadePerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedIdentidadeRoute,
  } as any)
const AuthenticatedPassaporteCapaRoute =
  AuthenticatedPassaporteCapaRouteImport.update({
    id: '/capa',
    path: '/capa',
    getParentRoute: () => AuthenticatedPassaporteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/brand-studio': typeof AuthenticatedBrandStudioRoute
  '/carimbos': typeof AuthenticatedCarimbosRouteWithChildren
  '/chapter-loop': typeof AuthenticatedChapterLoopRoute
  '/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/check-out': typeof AuthenticatedCheckOutRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRouteWithChildren
  '/identidade': typeof AuthenticatedIdentidadeRouteWithChildren
  '/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/carimbos/colecao': typeof AuthenticatedCarimbosColecaoRoute
  '/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/check-in/scanner': typeof AuthenticatedCheckInScannerRoute
  '/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/check-out/sincronizar': typeof AuthenticatedCheckOutSincronizarRoute
  '/diagnostico/inicial': typeof AuthenticatedDiagnosticoInicialRoute
  '/identidade/cartao': typeof AuthenticatedIdentidadeCartaoRoute
  '/identidade/perfil': typeof AuthenticatedIdentidadePerfilRoute
  '/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/brand-studio': typeof AuthenticatedBrandStudioRoute
  '/carimbos': typeof AuthenticatedCarimbosRouteWithChildren
  '/chapter-loop': typeof AuthenticatedChapterLoopRoute
  '/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/check-out': typeof AuthenticatedCheckOutRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRouteWithChildren
  '/identidade': typeof AuthenticatedIdentidadeRouteWithChildren
  '/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/carimbos/colecao': typeof AuthenticatedCarimbosColecaoRoute
  '/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/check-in/scanner': typeof AuthenticatedCheckInScannerRoute
  '/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/check-out/sincronizar': typeof AuthenticatedCheckOutSincronizarRoute
  '/diagnostico/inicial': typeof AuthenticatedDiagnosticoInicialRoute
  '/identidade/cartao': typeof AuthenticatedIdentidadeCartaoRoute
  '/identidade/perfil': typeof AuthenticatedIdentidadePerfilRoute
  '/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/brand-studio': typeof AuthenticatedBrandStudioRoute
  '/_authenticated/carimbos': typeof AuthenticatedCarimbosRouteWithChildren
  '/_authenticated/chapter-loop': typeof AuthenticatedChapterLoopRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/_authenticated/check-out': typeof AuthenticatedCheckOutRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRouteWithChildren
  '/_authenticated/identidade': typeof AuthenticatedIdentidadeRouteWithChildren
  '/_authenticated/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/carimbos/colecao': typeof AuthenticatedCarimbosColecaoRoute
  '/_authenticated/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/_authenticated/check-in/scanner': typeof AuthenticatedCheckInScannerRoute
  '/_authenticated/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/_authenticated/check-out/sincronizar': typeof AuthenticatedCheckOutSincronizarRoute
  '/_authenticated/diagnostico/inicial': typeof AuthenticatedDiagnosticoInicialRoute
  '/_authenticated/identidade/cartao': typeof AuthenticatedIdentidadeCartaoRoute
  '/_authenticated/identidade/perfil': typeof AuthenticatedIdentidadePerfilRoute
  '/_authenticated/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atendimento'
    | '/brand-studio'
    | '/carimbos'
    | '/chapter-loop'
    | '/check-in'
    | '/check-out'
    | '/cliente'
    | '/dashboard'
    | '/diagnostico'
    | '/identidade'
    | '/passaporte'
    | '/carimbos/colecao'
    | '/check-in/confirmacao'
    | '/check-in/scanner'
    | '/check-out/carimbado'
    | '/check-out/sincronizar'
    | '/diagnostico/inicial'
    | '/identidade/cartao'
    | '/identidade/perfil'
    | '/passaporte/capa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/atendimento'
    | '/brand-studio'
    | '/carimbos'
    | '/chapter-loop'
    | '/check-in'
    | '/check-out'
    | '/cliente'
    | '/dashboard'
    | '/diagnostico'
    | '/identidade'
    | '/passaporte'
    | '/'
    | '/carimbos/colecao'
    | '/check-in/confirmacao'
    | '/check-in/scanner'
    | '/check-out/carimbado'
    | '/check-out/sincronizar'
    | '/diagnostico/inicial'
    | '/identidade/cartao'
    | '/identidade/perfil'
    | '/passaporte/capa'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atendimento'
    | '/_authenticated/brand-studio'
    | '/_authenticated/carimbos'
    | '/_authenticated/chapter-loop'
    | '/_authenticated/check-in'
    | '/_authenticated/check-out'
    | '/_authenticated/cliente'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostico'
    | '/_authenticated/identidade'
    | '/_authenticated/passaporte'
    | '/_authenticated/'
    | '/_authenticated/carimbos/colecao'
    | '/_authenticated/check-in/confirmacao'
    | '/_authenticated/check-in/scanner'
    | '/_authenticated/check-out/carimbado'
    | '/_authenticated/check-out/sincronizar'
    | '/_authenticated/diagnostico/inicial'
    | '/_authenticated/identidade/cartao'
    | '/_authenticated/identidade/perfil'
    | '/_authenticated/passaporte/capa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brand-studio': {
      id: '/_authenticated/brand-studio'
      path: '/brand-studio'
      fullPath: '/brand-studio'
      preLoaderRoute: typeof AuthenticatedBrandStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carimbos': {
      id: '/_authenticated/carimbos'
      path: '/carimbos'
      fullPath: '/carimbos'
      preLoaderRoute: typeof AuthenticatedCarimbosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chapter-loop': {
      id: '/_authenticated/chapter-loop'
      path: '/chapter-loop'
      fullPath: '/chapter-loop'
      preLoaderRoute: typeof AuthenticatedChapterLoopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-out': {
      id: '/_authenticated/check-out'
      path: '/check-out'
      fullPath: '/check-out'
      preLoaderRoute: typeof AuthenticatedCheckOutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identidade': {
      id: '/_authenticated/identidade'
      path: '/identidade'
      fullPath: '/identidade'
      preLoaderRoute: typeof AuthenticatedIdentidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passaporte': {
      id: '/_authenticated/passaporte'
      path: '/passaporte'
      fullPath: '/passaporte'
      preLoaderRoute: typeof AuthenticatedPassaporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carimbos/colecao': {
      id: '/_authenticated/carimbos/colecao'
      path: '/colecao'
      fullPath: '/carimbos/colecao'
      preLoaderRoute: typeof AuthenticatedCarimbosColecaoRouteImport
      parentRoute: typeof AuthenticatedCarimbosRoute
    }
    '/_authenticated/check-in/confirmacao': {
      id: '/_authenticated/check-in/confirmacao'
      path: '/confirmacao'
      fullPath: '/check-in/confirmacao'
      preLoaderRoute: typeof AuthenticatedCheckInConfirmacaoRouteImport
      parentRoute: typeof AuthenticatedCheckInRoute
    }
    '/_authenticated/check-in/scanner': {
      id: '/_authenticated/check-in/scanner'
      path: '/scanner'
      fullPath: '/check-in/scanner'
      preLoaderRoute: typeof AuthenticatedCheckInScannerRouteImport
      parentRoute: typeof AuthenticatedCheckInRoute
    }
    '/_authenticated/check-out/carimbado': {
      id: '/_authenticated/check-out/carimbado'
      path: '/carimbado'
      fullPath: '/check-out/carimbado'
      preLoaderRoute: typeof AuthenticatedCheckOutCarimbadoRouteImport
      parentRoute: typeof AuthenticatedCheckOutRoute
    }
    '/_authenticated/check-out/sincronizar': {
      id: '/_authenticated/check-out/sincronizar'
      path: '/sincronizar'
      fullPath: '/check-out/sincronizar'
      preLoaderRoute: typeof AuthenticatedCheckOutSincronizarRouteImport
      parentRoute: typeof AuthenticatedCheckOutRoute
    }
    '/_authenticated/diagnostico/inicial': {
      id: '/_authenticated/diagnostico/inicial'
      path: '/inicial'
      fullPath: '/diagnostico/inicial'
      preLoaderRoute: typeof AuthenticatedDiagnosticoInicialRouteImport
      parentRoute: typeof AuthenticatedDiagnosticoRoute
    }
    '/_authenticated/identidade/cartao': {
      id: '/_authenticated/identidade/cartao'
      path: '/cartao'
      fullPath: '/identidade/cartao'
      preLoaderRoute: typeof AuthenticatedIdentidadeCartaoRouteImport
      parentRoute: typeof AuthenticatedIdentidadeRoute
    }
    '/_authenticated/identidade/perfil': {
      id: '/_authenticated/identidade/perfil'
      path: '/perfil'
      fullPath: '/identidade/perfil'
      preLoaderRoute: typeof AuthenticatedIdentidadePerfilRouteImport
      parentRoute: typeof AuthenticatedIdentidadeRoute
    }
    '/_authenticated/passaporte/capa': {
      id: '/_authenticated/passaporte/capa'
      path: '/capa'
      fullPath: '/passaporte/capa'
      preLoaderRoute: typeof AuthenticatedPassaporteCapaRouteImport
      parentRoute: typeof AuthenticatedPassaporteRoute
    }
  }
}

interface AuthenticatedCarimbosRouteChildren {
  AuthenticatedCarimbosColecaoRoute: typeof AuthenticatedCarimbosColecaoRoute
}

const AuthenticatedCarimbosRouteChildren: AuthenticatedCarimbosRouteChildren = {
  AuthenticatedCarimbosColecaoRoute: AuthenticatedCarimbosColecaoRoute,
}

const AuthenticatedCarimbosRouteWithChildren =
  AuthenticatedCarimbosRoute._addFileChildren(
    AuthenticatedCarimbosRouteChildren,
  )

interface AuthenticatedCheckInRouteChildren {
  AuthenticatedCheckInConfirmacaoRoute: typeof AuthenticatedCheckInConfirmacaoRoute
  AuthenticatedCheckInScannerRoute: typeof AuthenticatedCheckInScannerRoute
}

const AuthenticatedCheckInRouteChildren: AuthenticatedCheckInRouteChildren = {
  AuthenticatedCheckInConfirmacaoRoute: AuthenticatedCheckInConfirmacaoRoute,
  AuthenticatedCheckInScannerRoute: AuthenticatedCheckInScannerRoute,
}

const AuthenticatedCheckInRouteWithChildren =
  AuthenticatedCheckInRoute._addFileChildren(AuthenticatedCheckInRouteChildren)

interface AuthenticatedCheckOutRouteChildren {
  AuthenticatedCheckOutCarimbadoRoute: typeof AuthenticatedCheckOutCarimbadoRoute
  AuthenticatedCheckOutSincronizarRoute: typeof AuthenticatedCheckOutSincronizarRoute
}

const AuthenticatedCheckOutRouteChildren: AuthenticatedCheckOutRouteChildren = {
  AuthenticatedCheckOutCarimbadoRoute: AuthenticatedCheckOutCarimbadoRoute,
  AuthenticatedCheckOutSincronizarRoute: AuthenticatedCheckOutSincronizarRoute,
}

const AuthenticatedCheckOutRouteWithChildren =
  AuthenticatedCheckOutRoute._addFileChildren(
    AuthenticatedCheckOutRouteChildren,
  )

interface AuthenticatedDiagnosticoRouteChildren {
  AuthenticatedDiagnosticoInicialRoute: typeof AuthenticatedDiagnosticoInicialRoute
}

const AuthenticatedDiagnosticoRouteChildren: AuthenticatedDiagnosticoRouteChildren =
  {
    AuthenticatedDiagnosticoInicialRoute: AuthenticatedDiagnosticoInicialRoute,
  }

const AuthenticatedDiagnosticoRouteWithChildren =
  AuthenticatedDiagnosticoRoute._addFileChildren(
    AuthenticatedDiagnosticoRouteChildren,
  )

interface AuthenticatedIdentidadeRouteChildren {
  AuthenticatedIdentidadeCartaoRoute: typeof AuthenticatedIdentidadeCartaoRoute
  AuthenticatedIdentidadePerfilRoute: typeof AuthenticatedIdentidadePerfilRoute
}

const AuthenticatedIdentidadeRouteChildren: AuthenticatedIdentidadeRouteChildren =
  {
    AuthenticatedIdentidadeCartaoRoute: AuthenticatedIdentidadeCartaoRoute,
    AuthenticatedIdentidadePerfilRoute: AuthenticatedIdentidadePerfilRoute,
  }

const AuthenticatedIdentidadeRouteWithChildren =
  AuthenticatedIdentidadeRoute._addFileChildren(
    AuthenticatedIdentidadeRouteChildren,
  )

interface AuthenticatedPassaporteRouteChildren {
  AuthenticatedPassaporteCapaRoute: typeof AuthenticatedPassaporteCapaRoute
}

const AuthenticatedPassaporteRouteChildren: AuthenticatedPassaporteRouteChildren =
  {
    AuthenticatedPassaporteCapaRoute: AuthenticatedPassaporteCapaRoute,
  }

const AuthenticatedPassaporteRouteWithChildren =
  AuthenticatedPassaporteRoute._addFileChildren(
    AuthenticatedPassaporteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedBrandStudioRoute: typeof AuthenticatedBrandStudioRoute
  AuthenticatedCarimbosRoute: typeof AuthenticatedCarimbosRouteWithChildren
  AuthenticatedChapterLoopRoute: typeof AuthenticatedChapterLoopRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRouteWithChildren
  AuthenticatedCheckOutRoute: typeof AuthenticatedCheckOutRouteWithChildren
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRouteWithChildren
  AuthenticatedIdentidadeRoute: typeof AuthenticatedIdentidadeRouteWithChildren
  AuthenticatedPassaporteRoute: typeof AuthenticatedPassaporteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedBrandStudioRoute: AuthenticatedBrandStudioRoute,
  AuthenticatedCarimbosRoute: AuthenticatedCarimbosRouteWithChildren,
  AuthenticatedChapterLoopRoute: AuthenticatedChapterLoopRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRouteWithChildren,
  AuthenticatedCheckOutRoute: AuthenticatedCheckOutRouteWithChildren,
  AuthenticatedClienteRoute: AuthenticatedClienteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRouteWithChildren,
  AuthenticatedIdentidadeRoute: AuthenticatedIdentidadeRouteWithChildren,
  AuthenticatedPassaporteRoute: AuthenticatedPassaporteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
