/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPassaporteRouteImport } from './routes/_authenticated/passaporte'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPassaporteIntelligenceRouteImport } from './routes/_authenticated/passaporte-intelligence'
import { Route as AuthenticatedCarimbosColecaoRouteImport } from './routes/_authenticated/carimbos.colecao'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedCheckInConfirmacaoRouteImport } from './routes/_authenticated/check-in.confirmacao'
import { Route as AuthenticatedCheckOutIndexRouteImport } from './routes/_authenticated/check-out.index'
import { Route as AuthenticatedCheckOutCarimbadoRouteImport } from './routes/_authenticated/check-out.carimbado'
import { Route as AuthenticatedCheckOutSincronizarRouteImport } from './routes/_authenticated/check-out.sincronizar'
import { Route as AuthenticatedPassaporteCapaRouteImport } from './routes/_authenticated/passaporte.capa'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAtendimentoRoute = AuthenticatedAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedPassaporteRoute = AuthenticatedPassaporteRouteImport.update({
  id: '/passaporte',
  path: '/passaporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedPassaporteIntelligenceRoute =
  AuthenticatedPassaporteIntelligenceRouteImport.update({
    id: '/passaporte-intelligence',
    path: '/passaporte-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCarimbosColecaoRoute =
  AuthenticatedCarimbosColecaoRouteImport.update({
    id: '/colecao',
    path: '/colecao',
    getParentRoute: () => AuthenticatedPassaporteRoute,
  } as any)

const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedCheckInConfirmacaoRoute =
  AuthenticatedCheckInConfirmacaoRouteImport.update({
    id: '/confirmacao',
    path: '/confirmacao',
    getParentRoute: () => AuthenticatedCheckInRoute,
  } as any)

const AuthenticatedCheckOutIndexRoute =
  AuthenticatedCheckOutIndexRouteImport.update({
    id: '/check-out',
    path: '/check-out',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCheckOutCarimbadoRoute =
  AuthenticatedCheckOutCarimbadoRouteImport.update({
    id: '/check-out/carimbado',
    path: '/check-out/carimbado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCheckOutSincronizarRoute =
  AuthenticatedCheckOutSincronizarRouteImport.update({
    id: '/check-out/sincronizar',
    path: '/check-out/sincronizar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedPassaporteCapaRoute =
  AuthenticatedPassaporteCapaRouteImport.update({
    id: '/capa',
    path: '/capa',
    getParentRoute: () => AuthenticatedPassaporteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/passaporte-intelligence': typeof AuthenticatedPassaporteIntelligenceRoute
  '/passaporte/colecao': typeof AuthenticatedCarimbosColecaoRoute
  '/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/check-out': typeof AuthenticatedCheckOutIndexRoute
  '/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/check-out/sincronizar': typeof AuthenticatedCheckOutSincronizarRoute
  '/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/passaporte-intelligence': typeof AuthenticatedPassaporteIntelligenceRoute
  '/': typeof AuthenticatedIndexRoute
  '/passaporte/colecao': typeof AuthenticatedCarimbosColecaoRoute
  '/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/check-out': typeof AuthenticatedCheckOutIndexRoute
  '/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/check-out/sincronizar': typeof AuthenticatedCheckOutSincronizarRoute
  '/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/cliente': typeof AuthenticatedClienteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/_authenticated/passaporte-intelligence': typeof AuthenticatedPassaporteIntelligenceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/_authenticated/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/_authenticated/check-out': typeof AuthenticatedCheckOutIndexRoute
  '/_authenticated/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/_authenticated/check-out/sincronizar': typeof AuthenticatedCheckOutSincronizarRoute
  '/_authenticated/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
  '/_authenticated/passaporte/colecao': typeof AuthenticatedCarimbosColecaoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/atendimento'
    | '/auditoria'
    | '/cliente'
    | '/dashboard'
    | '/passaporte'
    | '/passaporte-intelligence'
    | '/passaporte/colecao'
    | '/check-in'
    | '/check-in/confirmacao'
    | '/check-out'
    | '/check-out/carimbado'
    | '/check-out/sincronizar'
    | '/passaporte/capa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/atendimento'
    | '/auditoria'
    | '/cliente'
    | '/dashboard'
    | '/passaporte'
    | '/passaporte-intelligence'
    | '/'
    | '/passaporte/colecao'
    | '/check-in'
    | '/check-in/confirmacao'
    | '/check-out'
    | '/check-out/carimbado'
    | '/check-out/sincronizar'
    | '/passaporte/capa'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/atendimento'
    | '/_authenticated/auditoria'
    | '/_authenticated/cliente'
    | '/_authenticated/dashboard'
    | '/_authenticated/passaporte'
    | '/_authenticated/passaporte-intelligence'
    | '/_authenticated/'
    | '/_authenticated/check-in'
    | '/_authenticated/check-in/confirmacao'
    | '/_authenticated/check-out'
    | '/_authenticated/check-out/carimbado'
    | '/_authenticated/check-out/sincronizar'
    | '/_authenticated/passaporte/capa'
    | '/_authenticated/passaporte/colecao'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRouteImport
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passaporte': {
      id: '/_authenticated/passaporte'
      path: '/passaporte'
      fullPath: '/passaporte'
      preLoaderRoute: typeof AuthenticatedPassaporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passaporte-intelligence': {
      id: '/_authenticated/passaporte-intelligence'
      path: '/passaporte-intelligence'
      fullPath: '/passaporte-intelligence'
      preLoaderRoute: typeof AuthenticatedPassaporteIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passaporte/colecao': {
      id: '/_authenticated/passaporte/colecao'
      path: '/colecao'
      fullPath: '/passaporte/colecao'
      preLoaderRoute: typeof AuthenticatedCarimbosColecaoRouteImport
      parentRoute: typeof AuthenticatedPassaporteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/confirmacao': {
      id: '/_authenticated/check-in/confirmacao'
      path: '/confirmacao'
      fullPath: '/check-in/confirmacao'
      preLoaderRoute: typeof AuthenticatedCheckInConfirmacaoRouteImport
      parentRoute: typeof AuthenticatedCheckInRoute
    }
    '/_authenticated/check-out': {
      id: '/_authenticated/check-out'
      path: '/check-out'
      fullPath: '/check-out'
      preLoaderRoute: typeof AuthenticatedCheckOutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-out/carimbado': {
      id: '/_authenticated/check-out/carimbado'
      path: '/check-out/carimbado'
      fullPath: '/check-out/carimbado'
      preLoaderRoute: typeof AuthenticatedCheckOutCarimbadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-out/sincronizar': {
      id: '/_authenticated/check-out/sincronizar'
      path: '/check-out/sincronizar'
      fullPath: '/check-out/sincronizar'
      preLoaderRoute: typeof AuthenticatedCheckOutSincronizarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passaporte/capa': {
      id: '/_authenticated/passaporte/capa'
      path: '/capa'
      fullPath: '/passaporte/capa'
      preLoaderRoute: typeof AuthenticatedPassaporteCapaRouteImport
      parentRoute: typeof AuthenticatedPassaporteRoute
    }
  }
}

interface AuthenticatedPassaporteRouteChildren {
  AuthenticatedCarimbosColecaoRoute: typeof AuthenticatedCarimbosColecaoRoute
  AuthenticatedPassaporteCapaRoute: typeof AuthenticatedPassaporteCapaRoute
}

const AuthenticatedPassaporteRouteChildren: AuthenticatedPassaporteRouteChildren = {
  AuthenticatedCarimbosColecaoRoute: AuthenticatedCarimbosColecaoRoute,
  AuthenticatedPassaporteCapaRoute: AuthenticatedPassaporteCapaRoute,
}

const AuthenticatedPassaporteRouteWithChildren =
  AuthenticatedPassaporteRoute._addFileChildren(
    AuthenticatedPassaporteRouteChildren,
  )

interface AuthenticatedCheckInRouteChildren {
  AuthenticatedCheckInConfirmacaoRoute: typeof AuthenticatedCheckInConfirmacaoRoute
}

const AuthenticatedCheckInRouteChildren: AuthenticatedCheckInRouteChildren = {
  AuthenticatedCheckInConfirmacaoRoute: AuthenticatedCheckInConfirmacaoRoute,
}

const AuthenticatedCheckInRouteWithChildren =
  AuthenticatedCheckInRoute._addFileChildren(AuthenticatedCheckInRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPassaporteRoute: typeof AuthenticatedPassaporteRouteWithChildren
  AuthenticatedPassaporteIntelligenceRoute: typeof AuthenticatedPassaporteIntelligenceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRouteWithChildren
  AuthenticatedCheckOutIndexRoute: typeof AuthenticatedCheckOutIndexRoute
  AuthenticatedCheckOutCarimbadoRoute: typeof AuthenticatedCheckOutCarimbadoRoute
  AuthenticatedCheckOutSincronizarRoute: typeof AuthenticatedCheckOutSincronizarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedClienteRoute: AuthenticatedClienteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPassaporteRoute: AuthenticatedPassaporteRouteWithChildren,
  AuthenticatedPassaporteIntelligenceRoute: AuthenticatedPassaporteIntelligenceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRouteWithChildren,
  AuthenticatedCheckOutIndexRoute: AuthenticatedCheckOutIndexRoute,
  AuthenticatedCheckOutCarimbadoRoute: AuthenticatedCheckOutCarimbadoRoute,
  AuthenticatedCheckOutSincronizarRoute: AuthenticatedCheckOutSincronizarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
