/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPassaporteRouteImport } from './routes/_authenticated/passaporte'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedCarimbosColecaoRouteImport } from './routes/_authenticated/carimbos.colecao'
import { Route as AuthenticatedCheckInConfirmacaoRouteImport } from './routes/_authenticated/check-in.confirmacao'
import { Route as AuthenticatedCheckOutIndexRouteImport } from './routes/_authenticated/check-out.index'
import { Route as AuthenticatedCheckOutCarimbadoRouteImport } from './routes/_authenticated/check-out.carimbado'
import { Route as AuthenticatedPassaporteCapaRouteImport } from './routes/_authenticated/passaporte.capa'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtendimentoRoute =
  AuthenticatedAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassaporteRoute = AuthenticatedPassaporteRouteImport.update({
  id: '/passaporte',
  path: '/passaporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedCarimbosColecaoRoute =
  AuthenticatedCarimbosColecaoRouteImport.update({
    id: '/carimbos/colecao',
    path: '/carimbos/colecao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInConfirmacaoRoute =
  AuthenticatedCheckInConfirmacaoRouteImport.update({
    id: '/confirmacao',
    path: '/confirmacao',
    getParentRoute: () => AuthenticatedCheckInRoute,
  } as any)
const AuthenticatedCheckOutIndexRoute =
  AuthenticatedCheckOutIndexRouteImport.update({
    id: '/check-out/',
    path: '/check-out/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckOutCarimbadoRoute =
  AuthenticatedCheckOutCarimbadoRouteImport.update({
    id: '/check-out/carimbado',
    path: '/check-out/carimbado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPassaporteCapaRoute =
  AuthenticatedPassaporteCapaRouteImport.update({
    id: '/capa',
    path: '/capa',
    getParentRoute: () => AuthenticatedPassaporteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/carimbos/colecao': typeof AuthenticatedCarimbosColecaoRoute
  '/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/check-out/': typeof AuthenticatedCheckOutIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/': typeof AuthenticatedIndexRoute
  '/carimbos/colecao': typeof AuthenticatedCarimbosColecaoRoute
  '/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/check-out': typeof AuthenticatedCheckOutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/passaporte': typeof AuthenticatedPassaporteRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/carimbos/colecao': typeof AuthenticatedCarimbosColecaoRoute
  '/_authenticated/check-in/confirmacao': typeof AuthenticatedCheckInConfirmacaoRoute
  '/_authenticated/check-out/carimbado': typeof AuthenticatedCheckOutCarimbadoRoute
  '/_authenticated/passaporte/capa': typeof AuthenticatedPassaporteCapaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/check-out/': typeof AuthenticatedCheckOutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/atendimento'
    | '/auditoria'
    | '/check-in'
    | '/cliente'
    | '/dashboard'
    | '/passaporte'
    | '/relatorios'
    | '/carimbos/colecao'
    | '/check-in/confirmacao'
    | '/check-out/carimbado'
    | '/passaporte/capa'
    | '/admin/'
    | '/check-out/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/atendimento'
    | '/auditoria'
    | '/check-in'
    | '/cliente'
    | '/dashboard'
    | '/passaporte'
    | '/relatorios'
    | '/'
    | '/carimbos/colecao'
    | '/check-in/confirmacao'
    | '/check-out/carimbado'
    | '/passaporte/capa'
    | '/admin'
    | '/check-out'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/atendimento'
    | '/_authenticated/auditoria'
    | '/_authenticated/check-in'
    | '/_authenticated/cliente'
    | '/_authenticated/dashboard'
    | '/_authenticated/passaporte'
    | '/_authenticated/relatorios'
    | '/_authenticated/'
    | '/_authenticated/carimbos/colecao'
    | '/_authenticated/check-in/confirmacao'
    | '/_authenticated/check-out/carimbado'
    | '/_authenticated/passaporte/capa'
    | '/_authenticated/admin/'
    | '/_authenticated/check-out/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passaporte': {
      id: '/_authenticated/passaporte'
      path: '/passaporte'
      fullPath: '/passaporte'
      preLoaderRoute: typeof AuthenticatedPassaporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/carimbos/colecao': {
      id: '/_authenticated/carimbos/colecao'
      path: '/carimbos/colecao'
      fullPath: '/carimbos/colecao'
      preLoaderRoute: typeof AuthenticatedCarimbosColecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in/confirmacao': {
      id: '/_authenticated/check-in/confirmacao'
      path: '/confirmacao'
      fullPath: '/check-in/confirmacao'
      preLoaderRoute: typeof AuthenticatedCheckInConfirmacaoRouteImport
      parentRoute: typeof AuthenticatedCheckInRoute
    }
    '/_authenticated/check-out/': {
      id: '/_authenticated/check-out/'
      path: '/check-out'
      fullPath: '/check-out/'
      preLoaderRoute: typeof AuthenticatedCheckOutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-out/carimbado': {
      id: '/_authenticated/check-out/carimbado'
      path: '/check-out/carimbado'
      fullPath: '/check-out/carimbado'
      preLoaderRoute: typeof AuthenticatedCheckOutCarimbadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passaporte/capa': {
      id: '/_authenticated/passaporte/capa'
      path: '/capa'
      fullPath: '/passaporte/capa'
      preLoaderRoute: typeof AuthenticatedPassaporteCapaRouteImport
      parentRoute: typeof AuthenticatedPassaporteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCheckInRouteChildren {
  AuthenticatedCheckInConfirmacaoRoute: typeof AuthenticatedCheckInConfirmacaoRoute
}

const AuthenticatedCheckInRouteChildren: AuthenticatedCheckInRouteChildren = {
  AuthenticatedCheckInConfirmacaoRoute: AuthenticatedCheckInConfirmacaoRoute,
}

const AuthenticatedCheckInRouteWithChildren =
  AuthenticatedCheckInRoute._addFileChildren(AuthenticatedCheckInRouteChildren)

interface AuthenticatedPassaporteRouteChildren {
  AuthenticatedPassaporteCapaRoute: typeof AuthenticatedPassaporteCapaRoute
}

const AuthenticatedPassaporteRouteChildren: AuthenticatedPassaporteRouteChildren =
  {
    AuthenticatedPassaporteCapaRoute: AuthenticatedPassaporteCapaRoute,
  }

const AuthenticatedPassaporteRouteWithChildren =
  AuthenticatedPassaporteRoute._addFileChildren(
    AuthenticatedPassaporteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRouteWithChildren
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPassaporteRoute: typeof AuthenticatedPassaporteRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCarimbosColecaoRoute: typeof AuthenticatedCarimbosColecaoRoute
  AuthenticatedCheckOutCarimbadoRoute: typeof AuthenticatedCheckOutCarimbadoRoute
  AuthenticatedCheckOutIndexRoute: typeof AuthenticatedCheckOutIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRouteWithChildren,
  AuthenticatedClienteRoute: AuthenticatedClienteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPassaporteRoute: AuthenticatedPassaporteRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCarimbosColecaoRoute: AuthenticatedCarimbosColecaoRoute,
  AuthenticatedCheckOutCarimbadoRoute: AuthenticatedCheckOutCarimbadoRoute,
  AuthenticatedCheckOutIndexRoute: AuthenticatedCheckOutIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
